[build]
target-dir = ".target"

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.x86_64-unknown-linux-gnu.env]
CC = "clang"
CXX = "clang++"
AR = "llvm-ar"
RANLIB = "llvm-ranlib"
